name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: damncrud
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      apache:
        image: php:7.4-apache
        ports:
          - 80:80

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP and Apache
      run: |
        sudo apt-get update
        sudo apt-get install -y php-mysql php-curl php-gd php-intl php-mbstring php-soap php-xml php-zip
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up database
      run: |
        mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS damncrud;"
        mysql -h 127.0.0.1 -u root damncrud < db/damncrud.sql
        
    - name: Copy files to web directory
      run: |
        sudo cp -r ./* /var/www/html/damncrud/
        sudo chmod -R 777 /var/www/html/damncrud/
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Download dummy profile image
      run: |
        mkdir -p helper
        wget -O helper/pp_baru.jpg https://via.placeholder.com/200x200.jpg
        
    - name: Run tests in parallel
      run: |
        python -m pytest helper/test_webapp.py -v -n 5
        
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: report/